name: parking_control
description: "A parking management app for Sr. João's parking lot."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  intl: ^0.19.0
  mask_text_input_formatter: ^2.9.0
  path: ^1.8.3
  path_provider: ^2.1.2
  pdf: ^3.10.7
  printing: ^5.12.0
  provider: ^6.1.1
  sqflite: ^2.3.2
  uuid: ^4.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8
  mocktail: ^1.0.4
  sqflite_common_ffi: ^2.3.5

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
